### ISSUE TITLE
[BUG]: gitmemoji.imam.dev not reachable

### ISSUE THREAD

**Issue by ThaDaVos** [ImBIOS/gitmemoji#12]
### Description of the bug

The website show on the repo is not available anymore: https://gitmemoji.imam.dev/

### Environment

N/A

### Steps To Reproduce

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ImBIOS** [comment]
Thank you for the report, It was solved just now.
The explanation on why this happened is that .dev is from Google domains, and Squarespace now acquires it.
And idk why, I need to re-connect it and solve it.
