### ISSUE TITLE
[FEAT]: Migrate from Styled-Component to TailwindCSS

### ISSUE THREAD

**Issue by ImBIOS** [ImBIOS/gitmemoji#3]
### Clear and concise description of the problem

As a contributor, it would be easier to maintain component-based development when we use Tailwind instead of styled-component.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by tymnec** [comment]
Assign this to me I would like to work on this.

**Comment by ImBIOS** [comment]
@tymnec Here you go 🚀

**Comment by ImBIOS** [comment]
@tymnec Please create a draft pull request if you still interested to working on this.

**Comment by tymnec** [comment]
Actually I was having some important work to do. But don't worry Sir I will do this within a day.
